# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoportal', '0002_auto_20171201_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='grade',
        ),
    ]
