# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoportal', '0005_auto_20171208_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('School-Wide', 'School-Wide'), ('Environmental-Initiatives', 'Environmental-Initiatives'), ('Interschool-Events', 'Interschool-Events'), ('Intraschool-Events', 'Intraschool-Events'), ('Social-Projects', 'Social-Projects'), ('Sports', 'Sports')], default='School-Wide', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='society',
            field=models.CharField(choices=[('All-Societies', 'All-Societies'), ('Computer', 'Computer'), ('Dance', 'Dance'), ('Drama', 'Drama'), ('Economics', 'Economics'), ('Maths', 'Maths'), ('MUN', 'MUN'), ('Music', 'Music'), ('Photography', 'Photography'), ('Quiz', 'Quiz'), ('Science', 'Science')], default='All-Societies', max_length=30),
        ),
    ]
