# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoportal', '0006_auto_20171208_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='house',
            field=models.CharField(choices=[('All-Houses', 'All-Houses'), ('Srishti', 'Srishti'), ('Sagar', 'Sagar'), ('Vasundhara', 'Vasundhara'), ('Himgiri', 'Himgiri')], default='All-Houses', max_length=30),
        ),
    ]
